name: ci
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: make deps-test
    - name: Lint
      run: make lint
    - name: Run tests
      run: make test

  publish:
    if: github.ref == 'refs/heads/master'
    needs: build

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install packaging dependencies
      run: make deps-dist
    - id: package
      name: Build packages
      run: |
        make dist-only
        make version-github-action
    - name: Echo package version
      run: |
        echo 'package version: ${{ steps.package.outputs.package_version }}'
        echo 'git revision: ${{ steps.package.outputs.git_revision }}'

    - uses: softprops/action-gh-release@v2
      with:
        name: Release v${{ steps.package.outputs.package_version }}
        tag_name: v${{ steps.package.outputs.package_version }}
        files: |
          dist/cfn-review-bot-${{ steps.package.outputs.package_version }}.tar.gz
          dist/cfn_review_bot-${{ steps.package.outputs.package_version }}-py3-none-any.whl
        fail_on_unmatched_files: true

    - name: Publish packages to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: make release-only
